# Generated by Django 4.0.1 on 2022-03-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('header', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('method', models.IntegerField(blank=True, null=True)),
                ('data', models.CharField(blank=True, max_length=255, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'interface',
                'managed': False,
            },
        ),
    ]
