# Generated by Django 4.0.1 on 2022-11-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('method', models.IntegerField(blank=True, null=True)),
                ('data', models.CharField(blank=True, max_length=255, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'interface',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Api',
        ),
    ]
