# Generated by Django 4.0.1 on 2022-12-04 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
